name: Deploy to Vercel

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Pull Vercel project config
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          vercel pull --yes --token=$VERCEL_TOKEN

      - name: Build
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          if [[ $GITHUB_EVENT_NAME == 'workflow_dispatch' ]]; then
            echo "üèóÔ∏è Building for Production"
            vercel build --prod --token=$VERCEL_TOKEN
          else
            echo "üèóÔ∏è Building for Preview"
            vercel build --token=$VERCEL_TOKEN
          fi

      - name: Deploy
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          if [[ $GITHUB_EVENT_NAME == 'workflow_dispatch' ]]; then
            echo "üöÄ Manual Production Deploy"
            vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
          else
            echo "üëÄ Preview Deploy"
            vercel deploy --prebuilt --token=$VERCEL_TOKEN
          fi
